namespace FinansalPusula.Services;

public record BistStock(string Symbol, string Name);

public static class BistDataService
{
    public static List<BistStock> AllStocks { get; } = new()
    {
        new("A1CAP", "A1 Capital Yatirim Menkul Degerler"),
        new("ACSEL", "Aciselsan Acipayam Seluloz"),
        new("ADEL", "Adel Kalemcilik"),
        new("ADESE", "Adese Gayrimenkul"),
        new("AEFES", "Anadolu Efes"),
        new("AFYON", "Afyon Cimento"),
        new("AGESA", "Agesa Hayat ve Emeklilik"),
        new("AGHOL", "Anadolu Grubu Holding"),
        new("AGROT", "Agrotech Teknoloji"),
        new("AKBNK", "Akbank"),
        new("AKCNS", "Akcansa"),
        new("AKENR", "Akenerji"),
        new("AKFGY", "Akfen GYO"),
        new("AKFYE", "Akfen Yenilenebilir Enerji"),
        new("AKGRT", "Aksigorta"),
        new("AKMGY", "Akmerkez GYO"),
        new("AKSA", "Aksa"),
        new("AKSEN", "Aksa Enerji"),
        new("AKSGY", "Akis GYO"),
        new("AKYHO", "Akdeniz Yatirim Holding"),
        new("ALARK", "Alarko Holding"),
        new("ALBRK", "Albaraka Turk"),
        new("ALCTL", "Alcatel Lucent Teletas"),
        new("ALFAS", "Alfa Solar Enerji"),
        new("ALGYO", "Alarko GYO"),
        new("ALKA", "Alkim Kagit"),
        new("ALKIM", "Alkim Kimya"),
        new("ALMAD", "Altinyag Madencilik"),
        new("ANELE", "Anel Elektrik"),
        new("ANGEN", "Anatolia Tani ve Biyoteknoloji"),
        new("ANHYT", "Anadolu Hayat Emeklilik"),
        new("ANSGR", "Anadolu Sigorta"),
        new("ARCLK", "Arcelik"),
        new("ARDYZ", "Ard Grup Bilisim"),
        new("ARENA", "Arena Bilgisayar"),
        new("ARSAN", "Arsan Tekstil"),
        new("ASGYO", "Asce GYO"),
        new("ASELS", "Aselsan"),
        new("ASTOR", "Astor Enerji"),
        new("ASUZU", "Anadolu Isuzu"),
        new("ATATP", "Atp Ticari Bilgisayar"),
        new("ATEK", "Atakule GYO"),
        new("ATLAS", "Atlas Menkul Kiymetler YO"),
        new("ATSYH", "Atlantis Yatirim Holding"),
        new("AVGYO", "Avrasya GYO"),
        new("AVHOL", "Avrupa Yatirim Holding"),
        new("AVOD", "Avod Gida ve Tarim"),
        new("AVTUR", "Avrasya Petrol ve Turistik Tesisler"),
        new("AYDEM", "Aydem Enerji"),
        new("AYEN", "Ayen Enerji"),
        new("AYGAZ", "Aygaz"),
        new("AZTEK", "Aztek Teknoloji"),
        new("BAGFS", "Bagfas"),
        new("BAKAB", "Bak Ambalaj"),
        new("BALAT", "Balatacilar Balatacilik"),
        new("BANVT", "Banvit"),
        new("BARMA", "Barem Ambalaj"),
        new("BASGZ", "Baskent Dogalgaz GYO"),
        new("BAYRK", "Bayrak Ebt Taban"),
        new("BEASL", "Besiktas Futbol"),
        new("BERA", "Bera Holding"),
        new("BEYAZ", "Beyaz Filo Oto Kiralama"),
        new("BFREN", "Bosch Fren Sistemleri"),
        new("BIENV", "Bien Yapi Urunleri"),
        new("BIGCH", "Buyuk Sefler Gida"),
        new("BIMAS", "Bim Birlesik Magazalar"),
        new("BIOEN", "Biotrend Cevre ve Enerji"),
        new("BOBET", "Bogazici Beton"),
        new("BORLS", "Borlease Otomotiv"),
        new("BORSK", "Borusan Yatirim"),
        new("BRISA", "Brisa"),
        new("BRKO", "Birko Birlesik Koyunlulular Mensucat"),
        new("BRKSN", "Berikosan"),
        new("BRMEN", "Birlik Mensucat"),
        new("BRSAN", "Borusan Mannesmann"),
        new("BRYAT", "Borusan Yatirim"),
        new("BSOKE", "Bati Soke Cimento"),
        new("BTCIM", "Bati Cimento"),
        new("BUCIM", "Bursa Cimento"),
        new("BURCE", "Burcelik"),
        new("BURVA", "Burcelik Vana"),
        new("BVSAN", "Bulbuloglu Vinc"),
        new("BYDNR", "Baydoner Restoranlari"),
        new("CANTE", "Can2 Termik"),
        new("CASA", "Casa Emtia"),
        new("CCOLA", "Coca-Cola Icecek"),
        new("CELHA", "Celik Halat"),
        new("CEMAS", "Cemas Dokum"),
        new("CEMTS", "Cemtas"),
        new("CEVRE", "Cevher"),
        new("CIMSA", "Cimsa"),
        new("CLEBI", "Celebi Hava Servisi"),
        new("CONSE", "Consus Enerji"),
        new("COSMO", "Cosmos Yatirim Holding"),
        new("CRDFA", "Creditwest Faktoring"),
        new("CUSAN", "Cuhadaroglu Metal"),
        new("CVKMD", "Cvk Maden Isletmeleri"),
        new("CWENE", "Cw Enerji"),
        new("DAGHL", "Dagi Yatirim Holding"),
        new("DAGI", "Dagi Giyim"),
        new("DAPGM", "Dap Gayrimenkul"),
        new("DARDL", "Dardanel"),
        new("DGATE", "Datagate Bilgisayar"),
        new("DGGYO", "Dogus GYO"),
        new("DGNMO", "Doganlar Mobilya"),
        new("DIRIT", "Dirilis Tekstil"),
        new("DITAS", "Ditas Dogan"),
        new("DMSAS", "Demisas Dokum"),
        new("DNISI", "Dinamik Isi Yalitim"),
        new("DOAS", "Dogus Otomotiv"),
        new("DOCO", "Do & Co"),
        new("DOGUB", "Dogusan"),
        new("DOHOL", "Dogan Holding"),
        new("DOKTA", "Doktas Dokumculuk"),
        new("DURDO", "Duran Dogan Basim"),
        new("DYOBY", "Dyo Boya"),
        new("DZGYO", "Deniz GYO"),
        new("EBEBK", "Ebebek Magazacilik"),
        new("ECILC", "Eczacibasi Ilac"),
        new("ECZYT", "Eczacibasi Yatirim"),
        new("EDATA", "E-Data Teknoloji"),
        new("EDIP", "Edip Gayrimenkul"),
        new("EGEEN", "Ege Endustri"),
        new("EGGUB", "Ege Gubre"),
        new("EGPOW", "Egeprofil"),
        new("EGYO", "Egs GYO"),
        new("EHKTY", "Erbakir"),
        new("EKGYO", "Emlak Konut GYO"),
        new("EKIZ", "Ekiz Kimya"),
        new("EKOS", "Ekos Teknoloji"),
        new("ELITE", "Elite Naturel Organik Gida"),
        new("EMKEL", "Emek Elektrik"),
        new("ENJSA", "Enerjisa Enerji"),
        new("ENKAI", "Enka Insaat"),
        new("ENSRI", "Enerya Enerji"),
        new("EPLAS", "Egeplast"),
        new("ERBOS", "Erbosan"),
        new("EREGL", "Eregli Demir Celik"),
        new("ERSU", "Ersu"),
        new("ESCOM", "Escort Teknoloji"),
        new("ESEN", "Esenboga Elektrik"),
        new("ETILR", "Etiler Gida"),
        new("EUPWR", "Europower Enerji"),
        new("EUREN", "Europen Endustri"),
        new("EYGYO", "Eyyo GYO"),
        new("FADE", "Fade Gida"),
        new("FENER", "Fenerbahce Futbol"),
        new("FLAP", "Flap Kongre Toplanti Hizmetleri"),
        new("FMIZP", "Federal Mogul Izmit Piston"),
        new("FONET", "Fonet Bilgi Teknolojileri"),
        new("FORMT", "Formet Metal ve Cam"),
        new("FORTE", "Forte Bilgi Iletisim"),
        new("FRIGO", "Frigo Pak Gida"),
        new("FROTO", "Ford Otosan"),
        new("FZLGY", "Fuzul GYO"),
        new("GARAN", "Garanti Bankasi"),
        new("GENIL", "Gen Ilac"),
        new("GENTS", "Gentas"),
        new("GEREL", "Gersan Elektrik"),
        new("GESAN", "Girisim Elektrik"),
        new("GIPTA", "Gipta Ofis Kirtasiye"),
        new("GLBMD", "Global Menkul Degerler"),
        new("GLCVY", "Gelecek Varlik Yonetimi"),
        new("GLRYH", "Guler Yatirim Holding"),
        new("GLYHO", "Global Yatirim Holding"),
        new("GOKNR", "Goknur Gida"),
        new("GOLTS", "Goltas Cimento"),
        new("GOODY", "Good-Year"),
        new("GOZDE", "Gozde Girisim"),
        new("GRNYO", "Garanti Yatirim Ortakligi"),
        new("GSDDE", "Gsd Denizcilik"),
        new("GSDHO", "Gsd Holding"),
        new("GUBRF", "Gubre Fabrikalari"),
        new("GWIND", "Galata Wind Enerji"),
        new("GZNMI", "Gezinomi Seyahat"),
        new("HALKB", "Halk Bankasi"),
        new("HATEK", "Hatay Tekstil"),
        new("HEDEF", "Hedef Holding"),
        new("HEKTS", "Hektas"),
        new("HKTM", "Hidropar Hareket Kontrol"),
        new("HLGYO", "Halk GYO"),
        new("HTTBT", "Hitit Bilgisayar"),
        new("HUBVC", "Hub Girisim"),
        new("HUNER", "Hun Enerji"),
        new("HURGZ", "Hurriyet Gzt."),
        new("ICBCT", "Icbct Turkey Bank"),
        new("IDGYO", "Idealist GYO"),
        new("IHEVA", "Ihlas Ev Aletleri"),
        new("IHLAS", "Ihlas Holding"),
        new("IHLGM", "Ihlas Gayrimenkul"),
        new("IHYAY", "Ihlas Yayin Holding"),
        new("IMASM", "Imas Makina"),
        new("INDES", "Indeks Bilgisayar"),
        new("INFO", "Info Yatirim"),
        new("INGRM", "Ingram Bilisim"),
        new("INTEM", "Intema"),
        new("IPEKE", "Ipek Dogal Enerji"),
        new("ISATR", "Is Bankasi (A)"),
        new("ISBTR", "Is Bankasi (B)"),
        new("ISCTR", "Is Bankasi (C)"),
        new("ISDMR", "Iskenderun Demir Celik"),
        new("ISFIN", "Is Finansal Kiralama"),
        new("ISGSY", "Is Girisim"),
        new("ISGYO", "Is GYO"),
        new("ISMEN", "Is Menkul Degerler"),
        new("ISSEN", "Isbir Sentetik Dokuma"),
        new("ISYAT", "Is Yatirim Ortakligi"),
        new("ITTFH", "Ittifak Holding"),
        new("IZENR", "Izdemir Enerji"),
        new("IZFAS", "Izmir Firca"),
        new("IZMDC", "Izmir Demir Celik"),
        new("JANTS", "Jantsa Jant Sanayi"),
        new("KAPLM", "Kaplamin"),
        new("KAREL", "Karel Elektronik"),
        new("KARSN", "Karsan Otomotiv"),
        new("KARTN", "Kartonsan"),
        new("KARYE", "Kartal Yenilenebilir Enerji"),
        new("KATMR", "Katmerciler Arac Ustu Ekipman"),
        new("KAYSE", "Kayseri Seker Fabrikasi"),
        new("KCAER", "Kocaer Celik"),
        new("KCHOL", "Koc Holding"),
        new("KFEIN", "Kafein Yazilim"),
        new("KGYO", "Koray GYO"),
        new("KIMMR", "Kiler Holding"),
        new("KLGYO", "Kiler GYO"),
        new("KLMSN", "Klimasan Klima"),
        new("KLNMA", "T. Kalkinma Bank."),
        new("KLRHO", "Kiler Holding"),
        new("KLSYN", "Kaleseramik"),
        new("KLYHO", "Klas Yatirim Holding"),
        new("KMPUR", "Kimteks Poliuretan"),
        new("KNFRT", "Konfrut Gida"),
        new("KONTR", "Kontrolmatik Teknoloji"),
        new("KONYA", "Konya Cimento"),
        new("KORDS", "Kordsa Teknik Tekstil"),
        new("KOZAA", "Koza Anadolu Metal"),
        new("KOZAL", "Koza Altin"),
        new("KRDMA", "Kardemir (A)"),
        new("KRDMB", "Kardemir (B)"),
        new("KRDMD", "Kardemir (D)"),
        new("KRGYO", "Korfez GYO"),
        new("KRONT", "Kron Teknoloji"),
        new("KRPLS", "Koroplast Temizlik"),
        new("KRSTL", "Kristal Kola"),
        new("KRTEK", "Karsu Tekstil"),
        new("KRVGD", "Kervan Gida"),
        new("KSTUR", "Kustur Kusadasi Turizm"),
        new("KUTPO", "Kutahya Porselen"),
        new("KUVVA", "Kuvva Gida"),
        new("KSTUR", "Kustur"),
        new("KZBGY", "Kizilbuk GYO"),
        new("KZGYO", "Kuzu Grup GYO"),
        new("LIDFA", "Lider Faktoring"),
        new("LINK", "Link Bilgisayar"),
        new("LMKDC", "Limak Dogu Anadolu Cimento"),
        new("LOGO", "Logo Yazilim"),
        new("LRSHO", "Lorash Holding"),
        new("LUKSK", "Luks Kadife"),
        new("MAALT", "Marmaris Altinyunus"),
        new("MACKO", "Mackolik"),
        new("MAGEN", "Margun Enerji"),
        new("MAKIM", "Makim Makina"),
        new("MAKTK", "Makina Takim"),
        new("MANAS", "Manas Enerji"),
        new("MARKA", "Marka Yatirim Holding"),
        new("MARTI", "Marti Otel"),
        new("MAVI", "Mavi Giyim"),
        new("MEDTR", "Mediterra Tıbbi Malzeme"),
        new("MEGAP", "Mega Polietilen"),
        new("MEPET", "Mepet Metro Petrol"),
        new("MERCN", "Mercan Kimya"),
        new("MERKO", "Merko Gida"),
        new("METRO", "Metro Holding"),
        new("METUR", "Metemtur Otelcilik"),
        new("MGCAS", "Mogul"),
        new("MGROS", "Migros Ticaret"),
        new("MIATK", "Mia Teknoloji"),
        new("MIPAZ", "Milpa"),
        new("MMCAS", "MMC Sanayi ve Ticari Yatirimlar"),
        new("MNDRS", "Menderes Tekstil"),
        new("MNDTR", "Mondi Turkey"),
        new("MOBTL", "Mobiltel Iletisim"),
        new("MPARK", "MLP Saglik (Medical Park)"),
        new("MRGYO", "Marti GYO"),
        new("MRSHL", "Marshall"),
        new("MSGYO", "Misir GYO"),
        new("MTRKS", "Matriks Bilgi Dagitim"),
        new("MTRYO", "Metro Yatirim Ortakligi"),
        new("MZHLD", "Mazhar Zorlu Holding"),
        new("NATEN", "Naturel Enerji"),
        new("NETAS", "Netas Telekomunizasyon"),
        new("NIBAS", "Nigde Beton"),
        new("NTGAZ", "Naturelgaz"),
        new("NTHOL", "Net Holding"),
        new("NUGYO", "Nurol GYO"),
        new("NUHCM", "Nuh Cimento"),
        new("OBAMS", "Oba Makarnacilik"),
        new("OBASE", "Obase Bilgisayar"),
        new("ODAS", "Odas Elektrik"),
        new("ONCSM", "Oncosem Onkolojik Sistemler"),
        new("ORCAY", "Orcay Ortakoy Cay"),
        new("ORGE", "Orge Enerji Elektrik"),
        new("ORMA", "Orma Orman Mahsulleri"),
        new("OSMEN", "Osmanli Menkul Degerler"),
        new("OSTIM", "Ostim Endustriyel Yatirimlar"),
        new("OTKAR", "Otokar"),
        new("OYAKC", "Oyak Cimento"),
        new("OYAYO", "Oyak Yatirim Ortakligi"),
        new("OYLUM", "Oylum Sinai Yatirimlar"),
        new("OZGYO", "Ozderici GYO"),
        new("OZKGY", "Ozak GYO"),
        new("OZRDN", "Ozerden Plastik"),
        new("OZSUB", "Ozsu Balik"),
        new("PAGYO", "Panora GYO"),
        new("PAMEL", "Pamel Yenilenebilir Elektrik"),
        new("PAPIL", "Papilon Savunma"),
        new("PARSN", "Parsan"),
        new("PASEU", "Pasifik Eurasia Lojistik"),
        new("PATEK", "Pasifik Teknoloji"),
        new("PCILT", "Pc Iletisim Medya"),
        new("PEGYO", "Pera GYO"),
        new("PENGD", "Penguen Gida"),
        new("PENTA", "Penta Teknoloji"),
        new("PETKM", "Petkim"),
        new("PETUN", "Pinar Et ve Un"),
        new("PGSUS", "Pegasus"),
        new("PINSU", "Pinar Su"),
        new("PKART", "Plastikkart"),
        new("PKENT", "Petrokent Turizm"),
        new("PLTUR", "Platform Turizm"),
        new("PNLSN", "Panelsan Cati Cephe"),
        new("PNSUT", "Pinar Sut"),
        new("POLHO", "Polisan Holding"),
        new("POLTK", "Politeknik Metal"),
        new("PRDGS", "Pardus Girisim"),
        new("PRKAB", "Turk Prysmian Kablo"),
        new("PRKME", "Park Elek.Madencilik"),
        new("PSGYO", "Pasifik GYO"),
        new("QNBFB", "Qnb Finansbank"),
        new("QNBFL", "Qnb Finans Finansal Kiralama"),
        new("QUAGR", "Qua Granite Hayal Yapi"),
        new("RALYH", "Ral Yatirim Holding"),
        new("RAYYS", "Ray Sigorta"),
        new("REEDR", "Reeder Teknoloji"),
        new("RNPOL", "Rainyday Polimer"),
        new("RODRG", "Rodrigo Tekstil"),
        new("RTALB", "Rta Laboratuvarlari"),
        new("RUBNS", "Rubenis Tekstil"),
        new("SAHOL", "Sabanci Holding"),
        new("SAMAT", "Saray Matbaacilik"),
        new("SANEL", "San-El Muhendislik"),
        new("SANFM", "Sanifoam Sunger"),
        new("SANKO", "Sanko Pazarlama"),
        new("SARKY", "Sarkuysan"),
        new("SASA", "Sasa Polyester"),
        new("SAYAS", "Say Yenilenebilir Enerji"),
        new("SDTTR", "Sdt Uzay ve Savunma"),
        new("SEKFK", "Seker Faktoring"),
        new("SEKUR", "Sekuro Plastik"),
        new("SELEC", "Selcuk Ecza Deposu"),
        new("SELGD", "Selcuk Gida"),
        new("SERVE", "Serve Film Produksiyon"),
        new("SEYKM", "Seyitler Kimya"),
        new("SILVR", "Silverline Endustri"),
        new("SISE", "Sise Cam"),
        new("SKBNK", "Sekerbank"),
        new("SKTAS", "Soktas"),
        new("SMART", "Smartiks Yazilim"),
        new("SMRTG", "Smart Gunes Enerjisi"),
        new("SNGYO", "Sinpas GYO"),
        new("SNICA", "Sanica Isi Sanayi"),
        new("SNKRN", "Senkron Yazilim"),
        new("SODSN", "Soda Sanayii"),
        new("SOKM", "Sok Marketler"),
        new("SONME", "Sonmez Filament"),
        new("SRVGY", "Servet GYO"),
        new("SUMAS", "Sumas Suni Tahta"),
        new("SUNTC", "Suntek Teknoloji"),
        new("SURGY", "Sur Tatil Evleri GYO"),
        new("SUWEN", "Suwen Magazacilik"),
        new("TABGD", "Tab Gida"),
        new("TARKM", "Tarkim Bitki Koruma"),
        new("TATGD", "Tat Gida"),
        new("TAVHL", "Tav Havalimanlari"),
        new("TCELL", "Turkcell"),
        new("TDGYO", "Trend GYO"),
        new("TEKTU", "Tek-Art Turizm"),
        new("TERA", "Tera Yatirim"),
        new("TETMT", "Tetamat Gida"),
        new("TGSAS", "Tgs Dis Ticaret"),
        new("THYAO", "Turk Hava Yollari"),
        new("TIRE", "Mondi Tire Kutsan"),
        new("TKNSA", "Teknosa"),
        new("TLMAN", "Trabzon Liman"),
        new("TMPOL", "Temapol Polimer"),
        new("TMSN", "Tumosan Motor"),
        new("TOASO", "Tofas Oto. Fab."),
        new("TRCAS", "Turcas Petrol"),
        new("TRGYO", "Torunlar GYO"),
        new("TRILC", "Turk Ilac Serum"),
        new("TSKB", "T.S.K.B."),
        new("TSPOR", "Trabzonspor Sportif"),
        new("TTKOM", "Turk Telekom"),
        new("TTRAK", "Turk Traktor"),
        new("TUCLK", "Tugcelik"),
        new("TUKAS", "Tukas"),
        new("TUPRS", "Tupras"),
        new("TUREX", "Turex Turizm"),
        new("TURGG", "Turcas Petrol"),
        new("TURSG", "Turkiye Sigorta"),
        new("UFUK", "Ufuk Yatirim"),
        new("ULAS", "Ulaslar Turizm"),
        new("ULKER", "Ulker Biskuvi"),
        new("ULUFA", "Ulusal Faktoring"),
        new("ULUSE", "Ulusoy Elektrik"),
        new("ULUYO", "Ulusoy Un"),
        new("UMPAS", "Umpas Holding"),
        new("UNLU", "Unlu Yatirim Holding"),
        new("USAK", "Usak Seramik"),
        new("VAKBN", "Vakiflar Bankasi"),
        new("VAKFN", "Vakif Finansal Kiralama"),
        new("VAKKO", "Vakko Tekstil"),
        new("VANGD", "Vanet Gida"),
        new("VBTYZ", "Vbt Yazilim"),
        new("VERTU", "Verusaturk Girisim"),
        new("VERUS", "Verusa Holding"),
        new("VESBE", "Vestel Beyaz Esya"),
        new("VESTL", "Vestel"),
        new("VKGYO", "Vakif GYO"),
        new("VKING", "Viking Kagit"),
        new("YAPRK", "Yaprak Sut ve Besi"),
        new("YAYLA", "Yayla Gida"),
        new("YBTAS", "Yibitas Yozgat Isci Birligi Insaat"),
        new("YEOTK", "Yeo Teknoloji"),
        new("YESIL", "Yesil Yatirim Holding"),
        new("YGGYO", "Yeni Gimat GYO"),
        new("YGYO", "Yesil GYO"),
        new("YKBNK", "Yapi ve Kredi Bank."),
        new("YNSN", "Yunsa"),
        new("YOTAS", "Yotas"),
        new("YUNSA", "Yunsa"),
        new("YYLGD", "Yayla Gida"),
        new("ZEDUR", "Zedur Enerji"),
        new("ZOREN", "Zorlu Enerji"),
        new("ZRGYO", "Ziraat GYO")
    };

    public static BistStock? FindStock(string query)
    {
        if (string.IsNullOrWhiteSpace(query)) return null;
        var upper = query.Trim().ToUpper();
        if (upper.EndsWith(".IS")) upper = upper.Substring(0, upper.Length - 3);

        return AllStocks.FirstOrDefault(s => s.Symbol == upper || s.Name.ToUpper().Contains(upper));
    }
}
